### ISSUE TITLE
Need to respond to: Error: MetaMask: Disconnected from MetaMask background. Page reload required.

### ISSUE THREAD

**Issue by stnbu** [stnbu/blacklist#3]
![Screen Shot 2021-05-14 at 8 58 55 AM](https://user-images.githubusercontent.com/4089758/118289570-b9c74000-b492-11eb-9f4e-abc875ebf26f.png)

![Screen Shot 2021-05-14 at 9 32 16 AM](https://user-images.githubusercontent.com/4089758/118293904-66a3bc00-b497-11eb-950e-a6ba19382fb6.png)

It looks like we need to respond to that. Can we reload a page? I think JS has that technology. How do we _accurately_ identify that error and respond?

**Comment by stnbu** [comment]
Note that none of the event listers we have set up as of [now](https://github.com/stnbu/blacklist/blob/cf96adb6cf87eb13b7b2093d61c3d5ce803609fd/www/index.js#L36) catch that before it happens. It just happens.

**Comment by stnbu** [comment]
Anther fucking update: Reloading the page does not fix this.

The MetaMask window says the following:

```
MetaMask encountered an error
Try again by closing and reopening the popup, or contact support here.
Error Details
* 		Message: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
* 		Code: Error 
* 		Stack:Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
* 		  at Mu (chrome-extension://lookawayimhidious/ui-libs.js:75:109949)
* 		  at chrome-extension://lookawayimhidious/ui-libs.js:75:57194
* 		  at za (chrome-extension://lookawayimhidious/ui-libs.js:75:66624)
* 		  at jl (chrome-extension://lookawayimhidious/ui-libs.js:75:104838)
* 		  at bu (chrome-extension://lookawayimhidious/ui-libs.js:75:90053)
* 		  at pu (chrome-extension://lookawayimhidious/ui-libs.js:75:89978)
* 		  at iu (chrome-extension://lookawayimhidious/ui-libs.js:75:87326)
* 		  at chrome-extension://lookawayimhidious/ui-libs.js:75:45768
* 		  at r.unstable_runWithPriority (chrome-extension://lookawayimhidious/ui-libs.js:172:3472)
* 		  at Vo (chrome-extension://lookawayimhidious/ui-libs.js:75:45477)
* 		  at Yo (chrome-extension://lookawayimhidious/ui-libs.js:75:45713)
* 		  at Ko (chrome-extension://lookawayimhidious/ui-libs.js:75:45648)
* 		  at eu (chrome-extension://lookawayimhidious/ui-libs.js:75:84115)
* 		  at Object.enqueueSetState (chrome-extension://lookawayimhidious/ui-libs.js:75:50429)
* 		  at t.x.setState (chrome-extension://lookawayimhidious/ui-libs.js:136:1461)
* 		  at chrome-extension://lookawayimhidious/ui-libs.js:93:48080
* 		  at n (chrome-extension://lookawayimhidious/ui-libs.js:19:98310)
* 		  at chrome-extension://lookawayimhidious/ui-libs.js:19:98540
* 		  at Array.forEach (<anonymous>)
* 		  at Object.notifyListeners (chrome-extension://lookawayimhidious/ui-libs.js:19:98510)
* 		  at S (chrome-extension://lookawayimhidious/ui-libs.js:19:102095)
* 		  at chrome-extension://lookawayimhidious/ui-libs.js:19:103236
* 		  at Object.confirmTransitionTo (chrome-extension://lookawayimhidious/ui-libs.js:19:98249)
* 		  at Object.push (chrome-extension://lookawayimhidious/ui-libs.js:19:103045)
* 		  at m.onSubmit (chrome-extension://lookawayimhidious/ui.js:152:1283770)
* 		  at async chrome-extension://lookawayimhidious/ui.js:152:1278565

// anonymized.
```

> Try again by closing and reopening the popup

There is no popup! Reloading the page does not fix it. I can only disable/enable the MetaMask extension and try again, at which point it fails, even if I've reloaded the page.

This happens also on other `window.ethereum`-enabled sites, like `cryptotots.io`.

How ever, this does not happen on another copy of this same wallet (yyes) on another computer.  Not on `cryptodollies.io` and *also* not on `/blacklist/`, so I think this is strictly MM issue.

But we still need to catch, react to this exception!!

**Comment by 0x36963** [comment]
haha
